name: Auto convert

on:
  schedule:
    - cron: '0 0 * * *'
  push:
  workflow_dispatch:

jobs:
  convert:
    name: Convert
    runs-on: ubuntu-latest
    container: ubuntu:latest
    defaults:
      run:
        shell: bash {0}
    steps:
      - name: Setup Ubuntu
        run: |
          apt update
          apt dist-upgrade -y
          apt install -y bash curl sudo git
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash - &&\
          sudo apt-get install -y nodejs
          npm i -g @adguard/hostlist-compiler
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run convert.sh
        run: |
          ./convert.sh
      - name: git commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add --all
          git commit -m "Update time: date"
          git push
